// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  /* thx to https://www.w3.org/TR/xml */
  this.xmlname_re_head = /a-zA-Z:_\xc0-\xd6\xd8-\xf6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\u{10000}-\u{effff}/u;

  this.xmlname_re_tail = /0-9\.\x2d\xb7\u0300-\u036f\u203f-\u2040/u;

  this.mktsname_re_tail = /0-9\x23\.\x2d\xb7\u0300-\u036f\u203f-\u2040/u;

  this.xmlname_re_anchored = RegExp(`^[${this.xmlname_re_head.source}][${this.xmlname_re_head.source}${this.xmlname_re_tail.source}]*$`, "u");

  this./* must NOT set global flag */xmlname_re_frontanchored = RegExp(`^[${this.xmlname_re_head.source}][${this.xmlname_re_head.source}${this.xmlname_re_tail.source}]*`, "u");

  this./* must NOT set global flag */xmlname_re_sticky = RegExp(`[${this.xmlname_re_head.source}][${this.xmlname_re_head.source}${this.xmlname_re_tail.source}]*`, "uy");

  this./* must NOT set global flag */mktsname_re_frontanchored = RegExp(`^[${this.xmlname_re_head.source}][${this.xmlname_re_head.source}${this.mktsname_re_tail.source}]*`, "u");

  this./* must NOT set global flag */mktsname_re_sticky = RegExp(`[${this.xmlname_re_head.source}][${this.xmlname_re_head.source}${this.mktsname_re_tail.source}]*`, "uy");

  /* must NOT set global flag */

}).call(this);

//# sourceMappingURL=_patterns.js.map
