// Generated by CoffeeScript 2.5.0
(function() {
  'use strict';
  var $, $drain, CND, DATOM, FS, INTERTEXT, LineBreaker, PATH, SP, alert, assign, badge, cast, debug, help, info, isa, join_path, jr, new_datom, rpr, select, type_of, types, urge, validate, warn, whisper;

  /*

  'Slab': the part of a word that is separated from others by breakpoints

  > The addressable unit of memory on the NCR 315 series is a "slab", short for "syllable", consisting of 12
  > data bits and a parity bit. Its size falls between a byte and a typical word (hence the name, 'syllable').
  > A slab may contain three digits (with at sign, comma, space, ampersand, point, and minus treated as
  > digits) or two alphabetic characters of six bits each.—[Wikipedia, "NCR
  > 315"](https://en.wikipedia.org/wiki/NCR_315)

  */
  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERTEXT/SLABS';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  PATH = require('path');

  FS = require('fs');

  ({jr} = CND);

  assign = Object.assign;

  join_path = function(...P) {
    return PATH.resolve(PATH.join(...P));
  };

  //...........................................................................................................
  types = require('./types');

  ({isa, validate, cast, type_of} = types);

  SP = require('steampipes');

  ({$, $drain} = SP.export());

  DATOM = require('datom');

  ({new_datom, select} = DATOM.export());

  INTERTEXT = null;

  LineBreaker = null;

  //===========================================================================================================

  //-----------------------------------------------------------------------------------------------------------
  this.slabs_from_text = function(text) {
    var R, end, ends, last_idx, lbo, line_breaker, prv_position, shy, slab, slabs, spc;
    /* NOTE

    Currently we use three single-character `end` markers:

    * `x`—'none': nothing (empty string) whether non-final or final
    * `_`—'space': space (U+0020) when non-final, nothing (empty string) when final
    * `|`—'hyphen': nothing when non-final, add hyphen (U+002d) when final

     */
    /* TAINT why doesn't import in top level work? */
    if (INTERTEXT == null) {
      INTERTEXT = require('..');
    }
    /* TAINT benchmark against https://github.com/hfour/linebreak-ts */
    if (LineBreaker == null) {
      LineBreaker = require('linebreak');
    }
    line_breaker = new LineBreaker(text);
    //.........................................................................................................
    shy = INTERTEXT.HYPH.soft_hyphen_chr;
    spc = '\x20';
    prv_position = 0;
    slabs = [];
    ends = [];
    R = {slabs, ends};
    //.........................................................................................................
    /* LBO: line break opportunity */
    while ((lbo = line_breaker.nextBreak()) != null) {
      end = 'x';
      slab = text.slice(prv_position, lbo.position);
      prv_position = lbo.position;
      last_idx = slab.length - 1;
      //.......................................................................................................
      switch (slab[last_idx]) {
        case shy:
          [end, slab] = ['|', slab.slice(0, last_idx)];
          break;
        /* TAINT in the future, we might want to consider other breaking (fixed or variable) spaces */
        case spc:
          [end, slab] = ['_', slab.slice(0, last_idx)];
      }
      //.......................................................................................................
      slabs.push(slab);
      ends.push(end);
    }
    //.........................................................................................................
    R.ends = R.ends.join('');
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.assemble = function(me, first_idx = null, last_idx = null) {
    var R, end, i, idx, ref, ref1;
    /* TAINT validate indexes? */
    if (first_idx == null) {
      first_idx = 0;
    }
    if (last_idx == null) {
      last_idx = me.slabs.length - 1;
    }
    first_idx = Math.max(first_idx, 0);
    last_idx = Math.min(last_idx, me.slabs.length - 1);
    R = '';
//.........................................................................................................
    for (idx = i = ref = first_idx, ref1 = last_idx; i <= ref1; idx = i += +1) {
      R += me.slabs[idx];
      switch (end = me.ends[idx]) {
        case 'x':
          null;
          break;
        case '_':
          (idx !== last_idx ? R += '\x20' : void 0);
          break;
        /* TAINT allow to configure hyphen */
        case '|':
          (idx === last_idx ? R += '-' : void 0);
          break;
        default:
          throw new Error(`^INTERTEXT/SLABS@4352^ unknown slab \`end\` option ${rpr(end)}`);
      }
    }
    //.........................................................................................................
    return R;
  };

}).call(this);

//# sourceMappingURL=slabs.js.map
